// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATex9hvxU8Ju-1OC_tohIEuLoiYMhzsH4',
    appId: '1:248633274767:web:0cdc5ef93a48ff09345bfa',
    messagingSenderId: '248633274767',
    projectId: 'panic-button-sanur',
    authDomain: 'panic-button-sanur.firebaseapp.com',
    storageBucket: 'panic-button-sanur.appspot.com',
    measurementId: 'G-GC2EKN3P1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPa1IeUe78Kul1VLu3AMv19o4WRJhtvdU',
    appId: '1:248633274767:android:6e6cfa0aecabbec4345bfa',
    messagingSenderId: '248633274767',
    projectId: 'panic-button-sanur',
    storageBucket: 'panic-button-sanur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ1neYrKhxlVRV1IFvOpwVXwdGMjS9EXE',
    appId: '1:248633274767:ios:b8345343480444d9345bfa',
    messagingSenderId: '248633274767',
    projectId: 'panic-button-sanur',
    storageBucket: 'panic-button-sanur.appspot.com',
    iosBundleId: 'com.example.sanurbali',
  );
}
